# Deployment configuration for Railway/Render/Heroku

# Railway deployment
[railway]
  template = "python"
  
[build]
  command = "pip install -r requirements.txt"
  
[deploy]
  command = "python app.py"
  
# Environment variables needed:
# GEMINI_API_KEY=your_gemini_api_key
# SERPAPI_KEY=your_serpapi_key
# PORT=5000
